config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'questions#index'

  resources :questions, except: %i[edit] do
    resources :answers, shallow: true, only: %i[create update destroy] do
      patch :best, on: :member
    end
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user

  validates :body, presence: true

  def mark_as_best!
    transaction do
      question.best_answer&.update!(best: false)
      update!(best: true)
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
  belongs_to :user

  validates :title, :body, presence: true

  def best_answer
    answers.find(&:best)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :questions
  has_many :answers
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def author_of?(resource)
    id == resource.user_id
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!, only: %i[create update best destroy]

  def create
    @answer = question.answers.new(answer_params)
    answer.user = current_user
    answer.save
  end

  def update
    if current_user.author_of?(answer)
      answer.update(answer_params)
    else
      redirect_to answer.question, notice: 'You have no rights to edit this answer.'
    end
  end

  def destroy
    if current_user.author_of?(answer)
      answer.destroy
    else
      redirect_to answer.question, notice: 'You have no rights to delete this answer.'
    end
  end

  def best
    if current_user.author_of?(answer.question)
      @best_before = answer.question.best_answer
      answer.mark_as_best!
    else
      redirect_to answer.question, notice: 'You have no rights to do this action.'
    end
  end

  private

  helper_method :question, :answer

  def question
    @question ||= Question.find(params[:question_id])
  end

  def answer
    @answer ||= params[:id] ? Answer.find(params[:id]) : question.answers.new
  end

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :load_question, only: %i[show update destroy]

  def index
    @questions = Question.all
  end

  def show
    @answer = @question.answers.new
  end

  def new
    @question = Question.new
  end

  def create
    @question = current_user.questions.new(question_params)
    if @question.save
      redirect_to @question, notice: 'Your question was successfully created.'
    else
      render :new
    end
  end

  def update
    if current_user.author_of?(@question)
      @question.update(question_params)
    else
      redirect_to @question, notice: 'You have no rights to edit this question.'
    end
  end

  def destroy
    if current_user.author_of?(@question)
      @question.destroy
      redirect_to questions_path, notice: 'Your question was successfully deleted.'
    else
      redirect_to @question, notice: 'You have no rights to delete this question.'
    end
  end

  private

  def load_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_answer.html.slim
- if answer.persisted?
  li.answer.list-group-item.px-0 id = "answer-#{answer.id}"
    .answer__best= render 'answers/best_answer', answer: answer

    p.mb-1= answer.body

    .d-flex.justify-content-between
      div
        small= answer.updated_at.strftime('%d.%m.%Y')
        small &nbsp;by&nbsp;
        small.text-muted= answer.user.name

      - if current_user&.author_of?(answer)
        .answer__actions.d-flex.justify-content-end
          = link_to 'Edit', '#', class: 'js-edit-answer-link mr-2'
          = link_to 'Delete', answer_path(answer), remote: true, method: :delete, data: { confirm: 'Are your sure?' }

    .answer__form
      = form_with model: answer, class: 'hide form' do |f|
        .answer__errors= render 'shared/errors', resource: answer
        .form-group
          = f.label :body
          = f.text_area :body, class: 'form-control'
        = f.submit 'Save', class: 'btn btn-primary'

app/views/answers/_best_answer.html.slim
- if answer.best?
  .mb-1.text-success.answer__best-text Best Answer
- elsif current_user&.author_of?(answer.question)
  = link_to 'Mark as the Best', best_answer_path(answer), method: :patch, remote: true, class: 'answer__best-link mb-1'

app/views/answers/_new.html.slim
= form_with model: [question, answer], class: 'new-answer form' do |f|
  .answer__errors= render 'shared/errors', resource: answer

  .form-group
    = f.label :body
    = f.text_area :body, class: 'form-control', rows: 4
  = f.submit 'Post your answer', class: 'btn btn-primary'

app/views/answers/best.js.erb
<% unless @best_before.nil? %>
  $('#answer-<%= @best_before.id %>').find('.answer__best').html('<%= j render "answers/best_answer", answer: @best_before %>');
<% end %>

$('#answer-<%= answer.id %>')
  .prependTo('.question__answers')
  .find('.answer__best')
  .html('<%= j render "answers/best_answer", answer: answer %>');

app/views/answers/create.js.erb
$('.new-answer .answer__errors').html('<%= render 'shared/errors', resource: answer %>');

<% if answer.persisted? %>
  $('.question__answers').append('<%= j render(answer) %>');
  $('.new-answer #answer_body').val('');
<% end %>

app/views/answers/destroy.js.erb
$('.notice').html('Your answer was successfully deleted.');
$('#answer-<%= answer.id %>').remove();

app/views/answers/update.js.erb
var $answerItem = $('#answer-<%= answer.id %>');

$answerItem
  .find('.answer__errors')
  .html('<%= render 'shared/errors', resource: answer %>');

<% unless answer.errors.present? %>
  $answerItem.replaceWith('<%= j render(answer) %>');
<% end %>

app/views/layouts/application.html.slim
doctype html
html
  head
    title Qna
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    = render 'shared/nav'
    .container
      div.notice= notice
      div.alert= alert
      = yield

app/views/questions/_form.html.slim
.question__errors
  = render 'shared/errors',resource: question

.question__form
  = form_with model: question, class: 'form' do |f|
    .form-group
      = f.label :title
      = f.text_field :title, class: 'form-control'
    .form-group
      = f.label :body
      = f.text_area :body, class: 'form-control', rows: 4

    = f.submit class: 'btn btn-primary'

app/views/questions/_question.html.slim
h1= question.title
p= question.body
p
  small= question.updated_at.strftime('%d.%m.%Y')
  small &nbsp;by&nbsp;
  small.text-muted= question.user.name

- if current_user&.author_of?(@question)
  .question__actions.d-flex
    = link_to 'Edit', '#', class: 'mr-3 js-question-edit-link'
    = link_to 'Delete', question_path(@question), method: :delete, data: { confirm: 'Are your sure?' }
  .question__edit.hide
    = render 'form', question: @question

app/views/questions/index.html.slim
h1 Questions

- if @questions.count == 0
  p No questions yet

ul.questions.mb-5
  - @questions.each do |question|
    li.question= link_to question.title, question

= link_to 'Ask question', new_question_path, class: 'btn btn-primary'

app/views/questions/new.html.slim
.row.justify-content-center
  .col-sm-6
    = render 'form', question: @question

app/views/questions/show.html.slim
.question.mb-5
  .question__info.mb-5
    = render 'question', question: @question

  ul.question__answers.list-group.list-group-flush
    = render @question.answers.order(best: :desc)

= render 'answers/new', question: @question, answer: @answer

app/views/questions/update.js.erb
var $questionItem = $('.question__info');

$questionItem
  .find('.question__errors')
  .html('<%= render 'shared/errors', resource: @question %>');

<% unless @question.errors.present? %>
  $questionItem.html('<%= j render(@question) %>');
<% end %>

app/views/shared/_errors.html.slim
- if resource&.errors.present?
  b= "#{resource.errors.count} error(s) detected: "
  ul
    - resource.errors.full_messages.each do |message|
      li= message

app/views/shared/_nav.html.slim
nav.navbar.navbar-light.bg-light.mb-3
  ul.navbar-nav.ml-auto
    - if user_signed_in?
      li.nav-item= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'nav-link'
    - else
      li.nav-item= link_to 'Sign in', new_user_session_path, class: 'nav-link'
      li.nav-item= link_to 'Sign up', new_user_registration_path, class: 'nav-link'